./manage.py rename_app organization-core organization_core
./manage.py rename_app organization-agenda organization_agenda
./manage.py rename_app organization-formats organization_formats
./manage.py rename_app organization-job organization_job
./manage.py rename_app organization-magazine organization_magazine
./manage.py rename_app organization-media organization_media
./manage.py rename_app organization-network organization_network
./manage.py rename_app organization-pages organization_pages
./manage.py rename_app organization-projects organization_projects
./manage.py rename_app organization-shop organization_shop